// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  x: __t.u32(),
  y: __t.u32(),
  energy: __t.f32(),
  size: __t.f32(),
  glyph: __t.string(),
  color: __t.string(),
  seeksFood: __t.bool().name("seeks_food"),
  fleesLarger: __t.bool().name("flees_larger"),
  aggression: __t.u8(),
  prompt: __t.string(),
  isPredator: __t.bool().name("is_predator"),
  kills: __t.u32(),
});
