// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gridSize: __t.u32().name("grid_size"),
  populationCap: __t.u32().name("population_cap"),
  foodCap: __t.u32().name("food_cap"),
  rngSeed: __t.u64().name("rng_seed"),
  tickCount: __t.u64().name("tick_count"),
  lastTickAt: __t.timestamp().name("last_tick_at"),
});
