// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gridSize: __t.u32().name("grid_size"),
  populationCap: __t.u32().name("population_cap"),
  foodCap: __t.u32().name("food_cap"),
  rngSeed: __t.u64().name("rng_seed"),
  tickCount: __t.u64().name("tick_count"),
  lastTickAt: __t.timestamp().name("last_tick_at"),
  bloomFoodMult: __t.f32().name("bloom_food_mult"),
  bloomBurnMult: __t.f32().name("bloom_burn_mult"),
  coldFoodMult: __t.f32().name("cold_food_mult"),
  coldBurnMult: __t.f32().name("cold_burn_mult"),
  ventFoodMult: __t.f32().name("vent_food_mult"),
  ventBurnMult: __t.f32().name("vent_burn_mult"),
  barrenFoodMult: __t.f32().name("barren_food_mult"),
  barrenBurnMult: __t.f32().name("barren_burn_mult"),
  foodSpawnPerTick: __t.u32().name("food_spawn_per_tick"),
});
