// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ClaimPowerupProcedure from "../claim_powerup_procedure";
import * as SpawnFromPromptProcedure from "../spawn_from_prompt_procedure";

export type ClaimPowerupArgs = __Infer<typeof ClaimPowerupProcedure.params>;
export type ClaimPowerupResult = __Infer<typeof ClaimPowerupProcedure.returnType>;
export type SpawnFromPromptArgs = __Infer<typeof SpawnFromPromptProcedure.params>;
export type SpawnFromPromptResult = __Infer<typeof SpawnFromPromptProcedure.returnType>;

