// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReducer from "../add_reducer";
import PlaceFoodReducer from "../place_food_reducer";
import RebalanceCreaturesReducer from "../rebalance_creatures_reducer";
import RegenerateTerrainReducer from "../regenerate_terrain_reducer";
import SayHelloReducer from "../say_hello_reducer";
import SetBiomeMultipliersReducer from "../set_biome_multipliers_reducer";
import SetFoodConfigReducer from "../set_food_config_reducer";
import SetGridSizeReducer from "../set_grid_size_reducer";
import SetLlmKeyReducer from "../set_llm_key_reducer";
import SetPlayerEmailReducer from "../set_player_email_reducer";
import SetPopulationCapReducer from "../set_population_cap_reducer";
import SetPopulationFloorReducer from "../set_population_floor_reducer";
import SetPowerupConfigReducer from "../set_powerup_config_reducer";
import SetTickSpeedReducer from "../set_tick_speed_reducer";
import SpawnPredatorReducer from "../spawn_predator_reducer";

export type AddParams = __Infer<typeof AddReducer>;
export type PlaceFoodParams = __Infer<typeof PlaceFoodReducer>;
export type RebalanceCreaturesParams = __Infer<typeof RebalanceCreaturesReducer>;
export type RegenerateTerrainParams = __Infer<typeof RegenerateTerrainReducer>;
export type SayHelloParams = __Infer<typeof SayHelloReducer>;
export type SetBiomeMultipliersParams = __Infer<typeof SetBiomeMultipliersReducer>;
export type SetFoodConfigParams = __Infer<typeof SetFoodConfigReducer>;
export type SetGridSizeParams = __Infer<typeof SetGridSizeReducer>;
export type SetLlmKeyParams = __Infer<typeof SetLlmKeyReducer>;
export type SetPlayerEmailParams = __Infer<typeof SetPlayerEmailReducer>;
export type SetPopulationCapParams = __Infer<typeof SetPopulationCapReducer>;
export type SetPopulationFloorParams = __Infer<typeof SetPopulationFloorReducer>;
export type SetPowerupConfigParams = __Infer<typeof SetPowerupConfigReducer>;
export type SetTickSpeedParams = __Infer<typeof SetTickSpeedReducer>;
export type SpawnPredatorParams = __Infer<typeof SpawnPredatorReducer>;

